"""add event table

Revision ID: ca4237aa1484
Revises: 28a146938964
Create Date: 2026-04-02 21:22:34.516383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4237aa1484'
down_revision: Union[str, None] = '28a146938964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('arrived', 'checked_in', 'loading_started', 'loading_finished', 'departed', name='event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('ingested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_event_org_idempotency_key')
    )
    op.create_index('ix_event_load_occurred_at', 'events', ['load_id', 'occurred_at'], unique=False)
    op.create_index('ix_event_stop_occurred_at', 'events', ['stop_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('ix_event_stop_occurred_at', table_name='events')
    op.drop_index('ix_event_load_occurred_at', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
