"""add detention case table

Revision ID: 716777b837a2
Revises: ca4237aa1484
Create Date: 2026-04-03 09:52:48.360558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716777b837a2'
down_revision: Union[str, None] = 'ca4237aa1484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detention_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='detention_case_status'), nullable=False),
    sa.Column('eligible_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.Column('free_minutes_applied', sa.Integer(), nullable=False),
    sa.Column('grace_minutes_applied', sa.Integer(), nullable=False),
    sa.Column('billable_unit_minutes_applied', sa.Integer(), nullable=False),
    sa.Column('dwell_minutes', sa.Integer(), nullable=False),
    sa.Column('billable_minutes', sa.Integer(), nullable=False),
    sa.Column('billable_units', sa.Integer(), nullable=False),
    sa.Column('rate_per_unit_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stop_id', name='uq_detention_case_stop_id')
    )
    op.create_index('ix_detention_case_load_id', 'detention_cases', ['load_id'], unique=False)
    op.create_index('ix_detention_case_org_status', 'detention_cases', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_detention_cases_id'), 'detention_cases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detention_cases_id'), table_name='detention_cases')
    op.drop_index('ix_detention_case_org_status', table_name='detention_cases')
    op.drop_index('ix_detention_case_load_id', table_name='detention_cases')
    op.drop_table('detention_cases')
    # ### end Alembic commands ###
